// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11R-joAy6yQAK5_0AuBqPFgQyjJbX3TU',
    appId: '1:273350446476:web:3edffb4e967b44aa5b5aa9',
    messagingSenderId: '273350446476',
    projectId: 'task-80e57',
    authDomain: 'task-80e57.firebaseapp.com',
    storageBucket: 'task-80e57.appspot.com',
    measurementId: 'G-30386ZNDN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD94Otme1i1GSFdUU3X3TstCrG8B-ThyRY',
    appId: '1:273350446476:android:a5828db01f9699725b5aa9',
    messagingSenderId: '273350446476',
    projectId: 'task-80e57',
    storageBucket: 'task-80e57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4LR3SxcrKOl8LdtY3ESx8dYl7JhKD8yI',
    appId: '1:273350446476:ios:b70433dd34e1a4155b5aa9',
    messagingSenderId: '273350446476',
    projectId: 'task-80e57',
    storageBucket: 'task-80e57.appspot.com',
    iosClientId: '273350446476-tbdvh0t98tle1c5puvgjs48sji75atg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4LR3SxcrKOl8LdtY3ESx8dYl7JhKD8yI',
    appId: '1:273350446476:ios:d6c7c3c7d54d219f5b5aa9',
    messagingSenderId: '273350446476',
    projectId: 'task-80e57',
    storageBucket: 'task-80e57.appspot.com',
    iosClientId: '273350446476-3jk4thtig06ae81nvflfqhgbtl1ve3ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.task.RunnerTests',
  );
}
